https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [ ]:
import numpy as np
np.random.random()          #np.random.random() → package(套件).module(模組).function(方法)
np.random.random(3)         #module裡有function、class、常數
np.random.random(size=3)    #實體裡有屬性、方法
np.random.random((3, 4))
np.random.random(size=(3, 4))

array([[0.5703056 , 0.14450869, 0.22059959, 0.43586192],
       [0.26748702, 0.61242927, 0.8996238 , 0.18755508],
       [0.86087271, 0.72962408, 0.31111081, 0.12264381]])

In [ ]:
from numpy.random import normal

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性 
type(normal_value)
normal_value.ndim   
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [18]:
#ndarray, 陣列運算
normal_value * 10

array([[ -5.72651742, -11.99089203, -17.8558741 ,   5.11194678],
       [ 20.68694188,   0.27229851,   7.52801943, -12.73269973],
       [  6.43644441,  -8.79726845,   5.88568301,  -1.31356543]])

In [ ]:
#ndarray, 統計方法 
normal_value.sum()
normal_value.sum(axis=0)    #加總normal_value縱向的值, 故會出來4個值
normal_value.sum(axis=1)    #加總normal_value橫向的值, 故會出來3個值

array([-3.04613368,  1.57545601,  0.22112935])